version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}

  app:
    image: simple2b/fan_ticket
    restart: always
    command: sh ./start_web.sh
    environment:
      APP_ENV: production
    depends_on:
      - db
    volumes:
      - ./.env:/home/app/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fan_ticket.rule=Host(`fan-ticket.simple2b.net`)"
      - "traefik.http.routers.fan_ticket.tls=true"
      - "traefik.http.routers.fan_ticket.tls.certresolver=myresolver"

  api:
    image: simple2b/fan_ticket
    restart: always
    command: sh ./start_api.sh
    environment:
      APP_ENV: production
      IS_API: "true"
      ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fan_ticket_api.rule=Host(`api.fan-ticket.simple2b.net`)"
      - "traefik.http.routers.fan_ticket_api.tls=true"
      - "traefik.http.routers.fan_ticket_api.tls.certresolver=myresolver"

volumes:
  db_data:
