version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}

  app:
    build:
        context: .
        dockerfile: Dockerfile
    image: simple2b/fan_ticket
    restart: always
    command: sh ./start_web.sh
    environment:
      APP_ENV: production
    depends_on:
      - db
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-8012}:8012
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fan_ticket.rule=Host(`fan-ticket.simple2b.net`)"
      - "traefik.http.routers.fan_ticket.tls=true"
      - "traefik.http.routers.fan_ticket.tls.certresolver=myresolver"

  api:
    build:
        context: .
        dockerfile: DockerfileApi
    image: simple2b/fan_ticket
    restart: always
    command: sh ./start_api.sh
    environment:
      APP_ENV: production
      IS_API: "true"
      ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
    depends_on:
      - db
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-8007}:8007
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fan_ticket.rule=Host(`fan-ticket.simple2b.net`)"
      - "traefik.http.routers.fan_ticket.tls=true"
      - "traefik.http.routers.fan_ticket.tls.certresolver=myresolver"

volumes:
  db_data:
