"""notifications_config

Revision ID: 079887b202ff
Revises: aaba16809f62
Create Date: 2023-11-22 18:02:59.925055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079887b202ff'
down_revision = 'aaba16809f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('new_event', sa.Boolean(), nullable=False),
    sa.Column('new_ticket', sa.Boolean(), nullable=False),
    sa.Column('new_message', sa.Boolean(), nullable=False),
    sa.Column('new_buyers_payment', sa.Boolean(), nullable=False),
    sa.Column('your_payment_received', sa.Boolean(), nullable=False),
    sa.Column('ticket_transfer_confirmed', sa.Boolean(), nullable=False),
    sa.Column('dispute_started', sa.Boolean(), nullable=False),
    sa.Column('dispute_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_configs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications_configs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_configs')
    # ### end Alembic commands ###
