"""limit_per_event

Revision ID: 0bb1bbd5e0e6
Revises: f2b818cd0e8f
Create Date: 2024-03-04 12:07:00.086166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb1bbd5e0e6'
down_revision = 'f2b818cd0e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_fee_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit_per_event', sa.Integer(), server_default='2', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_fee_settings', schema=None) as batch_op:
        batch_op.drop_column('limit_per_event')

    # ### end Alembic commands ###
