"""individual_fees_fix

Revision ID: 0c8170799d5c
Revises: d11fec416fb2
Create Date: 2024-03-25 14:19:05.656403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8170799d5c'
down_revision = 'd11fec416fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sellers_bank_fee', sa.Integer(), server_default=sa.text('NULL'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sellers_bank_fee')

    # ### end Alembic commands ###
