"""fee_settings

Revision ID: 11cc5f132030
Revises: b449c5249c17
Create Date: 2024-02-28 15:45:17.448610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cc5f132030'
down_revision = 'b449c5249c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_fee_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_fee', sa.Integer(), nullable=False),
    sa.Column('bank_fee', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_fee_settings'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_fee', sa.Integer(), server_default=sa.text('NULL'), nullable=True))
        batch_op.add_column(sa.Column('bank_fee', sa.Integer(), server_default=sa.text('NULL'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bank_fee')
        batch_op.drop_column('service_fee')

    op.drop_table('global_fee_settings')
    # ### end Alembic commands ###
