"""Add uuid to User

Revision ID: 12021aa0ac7b
Revises: 75be7da6af01
Create Date: 2024-02-04 19:38:35.118899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12021aa0ac7b'
down_revision = '75be7da6af01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_uuid')
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.create_index('ix_users_uuid', ['uuid'], unique=False)

    # ### end Alembic commands ###
