"""ticket_paid_to_seller

Revision ID: 265eeedacedf
Revises: fb5d762a2563
Create Date: 2024-02-14 14:54:16.406280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265eeedacedf'
down_revision = 'fb5d762a2563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_to_seller_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('paid_to_seller_at')

    # ### end Alembic commands ###
