"""Add uuid to user model

Revision ID: 29bf79471b7b
Revises: f6ea161d0001
Create Date: 2024-01-11 14:30:40.486125

"""
from alembic import op
import sqlalchemy as sa
from app import models as m

# revision identifiers, used by Alembic.
revision = '29bf79471b7b'
down_revision = 'f6ea161d0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    user_ids = op.get_bind().execute(sa.text("SELECT id FROM users")).fetchall()

    for user_id in user_ids:
        uuid = m.gen_uuid()
        op.get_bind().execute(sa.text(f"UPDATE users SET uuid = '{uuid}' WHERE id = {user_id[0]}"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
