"""locations_categories_deleted

Revision ID: 3a57b3a800c0
Revises: 81b692765068
Create Date: 2024-02-07 18:31:09.166760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a57b3a800c0'
down_revision = '81b692765068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
