"""disputes

Revision ID: 3ab57b9feaa1
Revises: aa16e2083cd7
Create Date: 2024-01-03 12:59:16.929394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ab57b9feaa1'
down_revision = 'aa16e2083cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispute')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unique_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='fk_dispute_buyer_id_users'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='fk_dispute_ticket_id_tickets'),
    sa.PrimaryKeyConstraint('id', name='pk_dispute')
    )
    # ### end Alembic commands ###
