"""phone_card_otional

Revision ID: 44573ea2d682
Revises: 079887b202ff
Create Date: 2023-12-04 16:08:10.816497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44573ea2d682'
down_revision = '079887b202ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('card',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('card',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
