"""ticket_fields_not_required

Revision ID: 46d4ecd9f1c9
Revises: 9d07ac169469
Create Date: 2023-12-21 14:48:07.067943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46d4ecd9f1c9"
down_revision = "9d07ac169469"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.alter_column("section", existing_type=sa.VARCHAR(length=16), nullable=True)
        batch_op.alter_column("queue", existing_type=sa.VARCHAR(length=16), nullable=True)
        batch_op.alter_column("seat", existing_type=sa.VARCHAR(length=16), nullable=True)
        batch_op.alter_column("price_net", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
        batch_op.alter_column("price_gross", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=sa.VARCHAR(length=64), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.alter_column("price_gross", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
        batch_op.alter_column("price_net", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
        batch_op.alter_column("seat", existing_type=sa.VARCHAR(length=16), nullable=False)
        batch_op.alter_column("queue", existing_type=sa.VARCHAR(length=16), nullable=False)
        batch_op.alter_column("section", existing_type=sa.VARCHAR(length=16), nullable=False)

    # ### end Alembic commands ###
