"""tickets_optional_buyer

Revision ID: 4ed4b0a55a09
Revises: 03b0fada405d
Create Date: 2023-12-08 17:05:00.957035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed4b0a55a09'
down_revision = '03b0fada405d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
