"""split_fees

Revision ID: 4faf7fe4ad5b
Revises: 0bb1bbd5e0e6
Create Date: 2024-03-25 11:04:00.960349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4faf7fe4ad5b'
down_revision = '0bb1bbd5e0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_fee_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_fee_buyer', sa.Integer(), server_default='2', nullable=False))
        batch_op.add_column(sa.Column('service_fee_seller', sa.Integer(), server_default='3', nullable=False))
        batch_op.add_column(sa.Column('bank_fee_buyer', sa.Integer(), server_default='4', nullable=False))
        batch_op.add_column(sa.Column('bank_fee_seller', sa.Integer(), server_default='2', nullable=False))
        batch_op.drop_column('bank_fee')
        batch_op.drop_column('service_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_fee_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_fee', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bank_fee', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('bank_fee_seller')
        batch_op.drop_column('bank_fee_buyer')
        batch_op.drop_column('service_fee_seller')
        batch_op.drop_column('service_fee_buyer')

    # ### end Alembic commands ###
