"""billing_address

Revision ID: 55a171558898
Revises: c5496d472c4c
Create Date: 2023-12-26 16:55:27.662688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a171558898'
down_revision = 'c5496d472c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_line_1', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('billing_line_2', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('billing_zip_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('billing_city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('billing_state', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('billing_country', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('billing_country')
        batch_op.drop_column('billing_state')
        batch_op.drop_column('billing_city')
        batch_op.drop_column('billing_zip_code')
        batch_op.drop_column('billing_line_2')
        batch_op.drop_column('billing_line_1')

    # ### end Alembic commands ###
