"""Notification -> Replace uuid name

Revision ID: 6a21d8e49b0b
Revises: 90ae4f23b480
Create Date: 2024-01-12 12:38:04.299550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a21d8e49b0b'
down_revision = '90ae4f23b480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.execute("UPDATE notifications SET uuid = unique_id")
        batch_op.alter_column('uuid', nullable=False)
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
