"""card_id

Revision ID: 6be5bbcb3574
Revises: f5d5437f235c
Create Date: 2023-12-26 18:00:29.148333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be5bbcb3574'
down_revision = 'f5d5437f235c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.String(length=16), nullable=True))
        batch_op.drop_column('card')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
        batch_op.drop_column('card_id')

    # ### end Alembic commands ###
