"""message_sender

Revision ID: 74811d52a2d0
Revises: 079887b202ff
Create Date: 2023-11-30 14:36:17.618839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74811d52a2d0'
down_revision = '079887b202ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
