"""Event venue

Revision ID: 75be7da6af01
Revises: aa90da3ad25a
Create Date: 2024-01-19 17:19:51.577938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75be7da6af01'
down_revision = 'aa90da3ad25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
