"""payment_subscribers

Revision ID: 7d7dd16d6f72
Revises: 0c3620ecc32a
Create Date: 2023-11-21 14:04:31.254528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7dd16d6f72'
down_revision = '0c3620ecc32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_events',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_users_events_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_events_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name=op.f('pk_users_events'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_payments_buyer_id_users')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_payments_event_id_events')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_payments_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('card', sa.String(length=16), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_card'), ['card'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_phone'), ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_phone'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_card'), type_='unique')
        batch_op.drop_column('card')
        batch_op.drop_column('phone')

    op.drop_table('payments')
    op.drop_table('users_events')
    # ### end Alembic commands ###
