"""global_settings_sorting

Revision ID: 7e524aba2283
Revises: 11cc5f132030
Create Date: 2024-02-29 16:02:01.555048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e524aba2283'
down_revision = '11cc5f132030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_fee_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tickets_sorting_by', sa.String(length=32), server_default='cheapest', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_fee_settings', schema=None) as batch_op:
        batch_op.drop_column('tickets_sorting_by')

    # ### end Alembic commands ###
