"""identity_document

Revision ID: 82aa6d0070e4
Revises: 9d07ac169469
Create Date: 2023-12-18 16:34:39.108176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82aa6d0070e4'
down_revision = '9d07ac169469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity_document_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_foreign_key(batch_op.f('fk_users_identity_document_id_pictures'), 'pictures', ['identity_document_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_identity_document_id_pictures'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.drop_column('identity_document_id')

    # ### end Alembic commands ###
