"""user_recipient_data

Revision ID: 88f0911ace0b
Revises: e7f5d2d746f2
Create Date: 2024-02-16 10:14:04.467448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f0911ace0b'
down_revision = 'e7f5d2d746f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('branch_check_digit', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('branch_number', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('account_check_digit', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_check_digit')
        batch_op.drop_column('account_number')
        batch_op.drop_column('branch_number')
        batch_op.drop_column('branch_check_digit')
        batch_op.drop_column('bank')

    # ### end Alembic commands ###
