"""Users notifications

Revision ID: 90ae4f23b480
Revises: 29bf79471b7b
Create Date: 2024-01-12 12:35:27.411464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ae4f23b480'
down_revision = '29bf79471b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_user_notification_notification_id_notifications')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_notification_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'notification_id', name=op.f('pk_user_notification'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_notification_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_last_notification_id_notifications'), 'notifications', ['last_notification_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_last_notification_id_notifications'), type_='foreignkey')
        batch_op.drop_column('last_notification_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_notifications_user_id_users', 'users', ['user_id'], ['id'])

    op.drop_table('user_notification')
    # ### end Alembic commands ###
