"""translations

Revision ID: 93181014ba6d
Revises: 0c8170799d5c
Create Date: 2024-03-26 14:43:04.293548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93181014ba6d'
down_revision = '0c8170799d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('en', sa.Text(), nullable=False),
    sa.Column('pt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    # ### end Alembic commands ###
