"""uuids

Revision ID: 94dace1bded1
Revises: 4be119030315
Create Date: 2023-10-30 15:24:44.253046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94dace1bded1'
down_revision = '4be119030315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('dispute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=False))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('dispute', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###
