"""individual_fees

Revision ID: d11fec416fb2
Revises: 4faf7fe4ad5b
Create Date: 2024-03-25 14:18:32.360798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11fec416fb2'
down_revision = '4faf7fe4ad5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyers_service_fee', sa.Integer(), server_default=sa.text('NULL'), nullable=True))
        batch_op.add_column(sa.Column('sellers_service_fee', sa.Integer(), server_default=sa.text('NULL'), nullable=True))
        batch_op.add_column(sa.Column('buyers_bank_fee', sa.Integer(), server_default=sa.text('NULL'), nullable=True))
        batch_op.drop_column('service_fee')
        batch_op.drop_column('bank_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_fee', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_fee', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('buyers_bank_fee')
        batch_op.drop_column('sellers_service_fee')
        batch_op.drop_column('buyers_service_fee')

    # ### end Alembic commands ###
