"""room_users

Revision ID: d2f8ff3547bd
Revises: d4f305c65855
Create Date: 2023-11-01 23:03:56.313075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f8ff3547bd'
down_revision = 'd4f305c65855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rooms_buyer_id_users'), 'users', ['buyer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_rooms_seller_id_users'), 'users', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rooms_seller_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_rooms_buyer_id_users'), type_='foreignkey')
        batch_op.drop_column('buyer_id')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
