"""reviews_fk

Revision ID: d4eaef2684a1
Revises: 834788adfa5a
Create Date: 2023-10-31 13:40:44.121347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4eaef2684a1'
down_revision = '834788adfa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_reviews',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='fk_users_reviews_review_id_reviews'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_reviews_user_id_users')
    )
    # ### end Alembic commands ###
