"""tickets_fk

Revision ID: d4f305c65855
Revises: d4eaef2684a1
Create Date: 2023-10-31 13:47:44.337285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f305c65855'
down_revision = 'd4eaef2684a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_tickets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tickets',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='fk_users_tickets_ticket_id_tickets'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_tickets_user_id_users')
    )
    # ### end Alembic commands ###
