"""pair_tickets

Revision ID: eacf655a82ec
Revises: 3d7b629a4816
Create Date: 2024-01-26 16:37:05.969439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacf655a82ec'
down_revision = '3d7b629a4816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paired', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('pair_unique_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('separate_selling_allowed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('wallet_id', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('last_reservation_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('price_net',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('price_gross',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('wallet_qr_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_qr_code', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.alter_column('price_gross',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('price_net',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('last_reservation_time')
        batch_op.drop_column('wallet_id')
        batch_op.drop_column('separate_selling_allowed')
        batch_op.drop_column('pair_unique_id')
        batch_op.drop_column('is_paired')

    # ### end Alembic commands ###
