# ruff: noqa: F401
from .auth import auth_blueprint
from .main import main_blueprint
from .events import events_blueprint
from .tickets import tickets_blueprint
from .admin import admin_blueprint
from .payments import pay_blueprint
from .notification import notification_blueprint
from .profile import blueprint_profile
from .chat import chat_blueprint
